### ISSUE TITLE
When handling EndNote data that contains only a single author, an error can arise

### ISSUE THREAD

**Issue by dxc111** [citation-js/plugin-enw#4]
Input: 
%0 Journal Article
%A Kerr, Graham S
%T An optically thin view of the flaring chromosphere: non-thermal widths in a chromospheric condensation during an X-class solar flare
%B Monthly Notices of the Royal Astronomical Society
%D 2023
%R 10.1093/mnras/stad3135
%J Monthly Notices of the Royal Astronomical Society
%V 527
%N 2
%P 2523-2548
%@ 0035-8711
%[ 12/7/2023
%U https://doi.org/10.1093/mnras/stad3135

When handling EndNote data that contains only a single author, an error can arise if the 'A' field, representing the author, is incorrectly typed as a string rather than an array. It is essential to format the 'A' field as an array for consistent processing, irrespective of the number of authors.

**Comment by larsgw** [comment]
Thank you for the bug report! I do not have access to many examples and the documentation is rather incomplete.
